import type { GitHubCommit } from "./types";

export function buildPrompt(username: string, commits: GitHubCommit[]): string {
  const commitMessages = commits
    .map(
      (commit) =>
        `${commit.repository.full_name} - ${commit.commit.message}`,
    )
    .join("\n");

  return `Create a professional LinkedIn post in Portuguese based ONLY on the GitHub commits below made by ${username}.

Do not invent technologies, features, bugs, results, learnings, goals, or other information that is not directly supported by the commit messages. If the commits do not provide enough evidence for a section, omit that section instead of guessing.

Use this structure when the available evidence supports it:

Nesta semana, foquei em [resumo do foco principal da semana].

💻 Avanços técnicos

[Concrete changes supported by the commits.]

📚 Tecnologias e conceitos aplicados

[Only technologies or concepts explicitly identifiable from the commits.]

🧠 Aprendizados da semana

[Only include learnings that can reasonably be derived from the actual work; do not invent personal experiences.]

📈 Próximos passos

[Only include next steps if they are explicitly present in the commits.]

Keep the tone professional and natural for LinkedIn. Do not mention that the post was generated by AI. Do not add a fabricated conclusion or engagement question.

Commits:
${commitMessages}`;
}
